---

- set_fact:
    previous_cf: "{{ item.tags | selectattr('key', 'equalto', 'Name') | map(attribute='value') | join(',')}}"

- cloudformation_facts:
    profile: "{{ boto_profile | default(omit) }}"
    region: "{{ wimpy_aws_region }}"
    stack_name: "{{ previous_cf }}"
    all_facts: true
  register: cf_facts

- name: "Delete ELB from DNS"
  route53:
    profile: "{{ boto_profile | default(omit) }}"
    region: "{{ wimpy_aws_region }}"
    command: create
    overwrite: True
    zone: "{{ wimpy_aws_hosted_zone_name }}"
    record: "{{ wimpy_aws_dns_name }}.{{ wimpy_aws_hosted_zone_name }}."
    identifier: "{{ previous_cf }}"
    weight: "0"
    ttl: "{{ wimpy_dns_ttl }}"
    type: "CNAME"
    value: "{{ cf_facts['ansible_facts']['cloudformation'][previous_cf]['stack_outputs']['LoadBalancer'] }}"
  when: wimpy_needs_elb

- name: "Waiting some seconds before removing previous CloudFormation"
  pause:
    seconds: "{{ wimpy_dns_ttl * 2 }}"

- name: "Remove previous CloudFormation"
  cloudformation:
    profile: "{{ boto_profile | default(omit) }}"
    region: "{{ wimpy_aws_region }}"
    stack_name: "{{ previous_cf }}"
    state: "absent"