---

- name: "Create new Launch Configuration"
  ec2_lc:
    profile: "{{ boto_profile | default(omit) }}"
    name: "{{ wimpy_project_name }}-{{ wimpy_release_version }}-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
    image_id: "{{ wimpy_aws_ami_id }}"
    key_name: "{{ wimpy_aws_keypair }}"
    region: "{{ wimpy_aws_region }}"
    security_groups: "{{ wimpy_aws_lc_security_groups }}"
    instance_type: "{{ wimpy_aws_instance_type }}"
    instance_profile_name: "{{ wimpy_role_instance_profile | default(omit) }}"
    assign_public_ip: yes
    user_data: "{{ wimpy_user_data }}"
  register: lc_result

- set_fact:
    wimpy_launch_config_name: "{{ lc_result.name }}"