---

- include_vars: "vars/{{ wimpy_deploy_strategy }}.yml"

- include: find_latest_ami.yml
  when: wimpy_aws_ami_id is undefined

- include: find_previous_cloudformation.yml
  when: wimpy_destroy_previous_asg

- include: create_launchconfiguration.yml

- include: launch_cloudformation_with_elb_dns.yml
  when: wimpy_needs_elb

- include: launch_cloudformation.yml
  when: not wimpy_needs_elb

- include: scaling_policies.yml

- include: clean_previous_cloudformation.yml
  when:
    - wimpy_destroy_previous_asg
    - previous_asgs.results | count > 0