---

- name: "Search previous CloudFormations"
  ec2_asg_facts:
    profile: "{{ boto_profile | default(omit) }}"
    region: "{{ wimpy_aws_region }}"
    name: "{{ wimpy_project_name }}*"
    tags:
      Stack: "{{ wimpy_project_name }}"
      Environment: "{{ wimpy_deployment_environment }}"
  register: previous_asgs
