---

- include: check_vars.yml

- include: "{{ wimpy_before_build_tasks_file | default('empty.yml') }}"

- include: build_docker_image.yml

- include: "{{ wimpy_before_deploy_tasks_file | default('empty.yml') }}"

- include: deploy.yml

- include: "{{ wimpy_after_deploy_tasks_file | default('empty.yml') }}"

- include: clean_launchconfigurations.yml