---

- name: "Update Github Deployment status"
  uri:
    url: "{{ github_deployments_api }}/{{ github_deployment.json.id }}/statuses"
    method: POST
    headers:
      Authorization: "Token {{ wimpy_github_token }}"
      Content-Type: "application/json"
    body:
      state: "success"
      target_url: ""
      description: "Deployment finished successfully"
    status_code: 201
    body_format: json
  when: wimpy_github_project_url != ''